### ISSUE TITLE
Waves generator

### ISSUE THREAD

**Issue by ozonexo3** [ozonexo3/FAForeverMapEditor#10]
Generator for waves. Need to find shore line and create waves from preset at given shoreline depth, same as in official editor.

It should be simplified, because not every wave type is used.

Rendering should be done using ParticleSystem.

**Comment by wgabel** [comment]
Any idea how to implement this? How this will transfer to FA? What system in FA does support this?

**Comment by zkov96** [comment]
You can see standart coop mission as X1CA_001.scmap find *wave*.dds analyze around data vor Vector3D. Also you can decompile basic based map editor for this data structure.

**Comment by zkov96** [comment]
See to file ./ScenarioEditor_Code/ScenarioEditor/wave.cs
I particly comment this code.
[ScenarioEditor_Code.zip](https://github.com/ozonexo3/FAForeverMapEditor/files/4606943/ScenarioEditor_Code.zip)

**Comment by ozonexo3** [comment]
Wave generator are just simple particle emitters. We only have position, rotation, velocity and other particle data like texture and lifetime. 
https://github.com/ozonexo3/FAForeverMapEditor/blob/master/Assets/Scripts/HazardX%20SCMAP%20Code/WaveGenerator.cs

The real issue with this is that we need to find positions and rotations for all emitters. It need to be on the water surface, near land (how far from shore should be controlled by user) and rotated into the land. Other data can be just copy/pasted from other waves from other maps with randomized Period and Scale.

**Comment by ozonexo3** [comment]
Added in v0.700
