### ISSUE TITLE
Marker: improve description of "too close to the edge!" warning

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#107]
hey, ppl are wondering what that warning is about.
Maybe the description should explain that the AI can't build those resources (<=8 game units).

We could also add a warning if the buildspace of a building gets closer than 2,5 game units. In that case you will not be place the building in game.
![image](https://user-images.githubusercontent.com/28671151/59696753-e2822480-91ec-11e9-9aac-c604aab1d078.png)

**Comment by ozonexo3** [comment]
Implemented in v0.701
![image](https://user-images.githubusercontent.com/9513043/104570522-55b27d80-5652-11eb-965b-04a6d53da6fe.png)
