### ISSUE TITLE
add copy & paste

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#109]
hey,
since it is a recurring theme in M&M I had to place the request here ;)
If you ask me I would like it for marker, props, decals and units.
But simply ignore the request for now if you are busy elsewhere.

**Comment by wgabel** [comment]
As I understand this is already implemented.

**Comment by ozonexo3** [comment]
It was still missing copy/paste for markers. Now its fully implemented ;)
