### ISSUE TITLE
is this still being worked on?

### ISSUE THREAD

**Issue by cyndernight** [ozonexo3/FAForeverMapEditor#110]
hi,  is the faf map editor still being worked on?

theirs 2 features i would kill (or more likely bank roll) to be added.

1 is a ruler, some way to place "point A" down and measure distance from "point A" to the mouse tip...

2: unit arcs... some way to see "if i places a unit here, how far can it shoot"....

i cant see a way to do this already so i would love to see this added... and if not too expensive i could bankroll this, paying you for your time to add these features in?

thanks for ya time.

**Comment by ozonexo3** [comment]
Yes editor is still worked on but I don't have a lot of free time. I will try to add it in this month.

I will not give you any price because Im not doing it for money, but if you want to donate here is a paypal donation link [DONATE](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=LUYMTPBDH5V4E&lc=GB&item_name=FAF%20Map%20Editor&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted)

**Comment by cyndernight** [comment]
@ozonexo3 
i understand the lack of free time, can be a pain sometimes.
the additions would be very helpful for trying to work out ranges and distances...

well, how much do you think is a fare tip for taking time out of your busy life and doing this?  how long will it take to code?  what do you think is fair?

<3

**Comment by ozonexo3** [comment]
Anything will be great, I really don't expect anything from anybody. It should take me around one evening or something.

**Comment by cyndernight** [comment]
@ozonexo3 
well, ya know, your taking your time to do something for a total stranger just because they asked ya to...  it seams only fair to me to give back for the kindness and compassion, since i cant offer my code (you wouldn't want it anyway, its terrible) i figure i can offer a donation

i get paid this weekend, ill make sure your donation is on top of the to-do list regardless if the features are deployed or not <3

if you remember, could you give me an @ sometime when the features are in? 
im not sure if theres a way to get an email alert if the project updates or something...

**Comment by ozonexo3** [comment]
I can write comment here with update when it will be available. Then you should get an email with notification. You should also see when this issue will be closed.

**Comment by cyndernight** [comment]
@ozonexo3 

that would be wonderful, thank you so much <3

**Comment by ozonexo3** [comment]
Hi. Just implemented Ruler feature.

Get **v0.605 WIP7**
https://github.com/ozonexo3/FAForeverMapEditor/releases/tag/v0.605-WIP-alpha

WIP builds are work in progress and we are testing them for bugs.

**Comment by ozonexo3** [comment]
Units weapon ranges and basic information about selected units has been implemented in **v0.605 WIP8**

https://github.com/ozonexo3/FAForeverMapEditor/releases/tag/v0.605-WIP-alpha
