### ISSUE TITLE
Remove Map Upload Through Editor

### ISSUE THREAD

**Issue by CouncillorMorax** [ozonexo3/FAForeverMapEditor#112]
The current issues of map vault rule violation is overwhelming the M&M team plus moderation to the point where a "whitelist" must be implemented to allow a user to upload content.

Since there is an option to upload maps through the editor, FAF moderation cannot make this happen as it is a loophole in the logic.

Please see image below for an example, and / or follow up with myself, Gorton, or Philip for details.

https://i.imgur.com/rwznFY8.jpg

**Comment by ozonexo3** [comment]
Removed in v0.605
