### ISSUE TITLE
difference in marker naming

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#113]
I was wondering why the `AI Naval Expansion Limit` was not working for my new map. I got in touch with Uveso and we were able to identify the Issue.

The AI is unable to count/index marker named like `NavalArea_XX` (FAF Editor).
![marker_name_faf_editor](https://user-images.githubusercontent.com/28671151/70529329-8fac7880-1b50-11ea-8bcb-c6ac5e98c73b.JPG)

According to Uveso all AI's are searching for `Naval Area` (with space) for indexing, like in the old marker names `Naval Area XX` (GPG editor): https://github.com/FAForever/fa/blob/develop/lua/aibrain.lua#L1098
![marker_name_gpg_editor](https://user-images.githubusercontent.com/28671151/70529334-920ed280-1b50-11ea-826c-74743620688c.JPG)

That's the reason why the `AI Naval Expansion Limit` is not working for maps created in the FAF Editor. It would be nice to adapt the marker name. This way the AI works properly on GPG and FAF editor maps without changing/adapting all AI code.

About naming:
For the AI its enough to name it like this `Naval Area_XX`.
I'm not sure if any other marker name should be changed, can you think of any other critical marker?
Maybe we should consider naming all marker like the GPG ones to avoid any future problem?!

**Comment by badbwoi** [comment]
it seem that `ExpansionArea_XX` needs to be changed as well: https://github.com/FAForever/fa/blob/develop/lua/aibrain.lua#L1100`
The code is looking for `Expansion Area`.

**Comment by Uveso** [comment]
These are the searching strings for markers:
```LUA
string.find(k, 'ARMY_')
string.find(k, 'Naval Area')
string.find(k, 'Expansion Area')
string.find(k, 'EXPANSION_AREA')
string.find(k, 'Large Expansion')
```

**Comment by ozonexo3** [comment]
Done.
Also added button in Markers to fix all AI marker names for already existing markers that has wrong names.
