### ISSUE TITLE
Crash! (Exception)

### ISSUE THREAD

**Issue by OnlyVenusProject** [ozonexo3/FAForeverMapEditor#114]
![WTF](https://user-images.githubusercontent.com/49580686/70841230-dc7ea080-1e29-11ea-962a-ba29112ab145.jpg)

Wtf?

**Comment by ozonexo3** [comment]
Please send log file, without it I'm unable to help.
Make sure you are using the latest build (right now v0.605) and your paths to the game and maps folder in **Edit/Preferences** are correct

**Comment by Soft-2019** [comment]
getting the same error on new maps and old just upgraded from version 604. heres my log 

Initialize engine version: 2018.2.2f1 (c18cef34cbcd)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Radeon RX 580 Series (ID=0x67df)
    Vendor:   
    VRAM:     8137 MB
    Driver:   26.20.12028.2
Begin MonoManager ReloadAssembly
Unable to find type [UnityEngine.CoreModule.dll]UnityEngine.Experimental.PlayerLoop.EarlyUpdate/CloudWebServicesUpdate
 
(Filename:  Line: 126)

Unable to find type [UnityEngine.CoreModule.dll]UnityEngine.Experimental.PlayerLoop.EarlyUpdate/UnityConnectClientUpdate
 
(Filename:  Line: 126)

Unable to find type [UnityEngine.CoreModule.dll]UnityEngine.Experimental.PlayerLoop.EarlyUpdate/UpdateAllUnityWebStreams
 
(Filename:  Line: 126)

Unable to find type [UnityEngine.CoreModule.dll]UnityEngine.Experimental.PlayerLoop.PostLateUpdate/ParticlesLegacyUpdateAllParticleSystems
 
(Filename:  Line: 126)

Unable to find type [UnityEngine.CoreModule.dll]UnityEngine.Experimental.PlayerLoop.PreLateUpdate/EndGraphicsJobsLate
 
(Filename:  Line: 126)

Unable to find method CleanupRenderPipeline in [UnityEngine.CoreModule.dll]UnityEngine.Experimental.Rendering.RenderPipelineManager
 
(Filename:  Line: 143)

Unable to find method DoRenderLoop_Internal in [UnityEngine.CoreModule.dll]UnityEngine.Experimental.Rendering.RenderPipelineManager
 
(Filename:  Line: 143)

Unable to find method FallbackMixedLightingModeByRef in [UnityEngine.CoreModule.dll]UnityEngine.Experimental.Rendering.SupportedRenderingFeatures
 
(Filename:  Line: 143)

Unable to find method IsLightmapBakeTypeSupportedByRef in [UnityEngine.CoreModule.dll]UnityEngine.Experimental.Rendering.SupportedRenderingFeatures
 
(Filename:  Line: 143)

Unable to find method IsLightmapsModeSupportedByRef in [UnityEngine.CoreModule.dll]UnityEngine.Experimental.Rendering.SupportedRenderingFeatures
 
(Filename:  Line: 143)

Unable to find method IsMixedLightingModeSupportedByRef in [UnityEngine.CoreModule.dll]UnityEngine.Experimental.Rendering.SupportedRenderingFeatures
 
(Filename:  Line: 143)

Unable to find method DoSendMouseEvents in [UnityEngine.CoreModule.dll]UnityEngine.SendMouseEvents
 
(Filename:  Line: 143)

Unable to find method SetMouseMoved in [UnityEngine.CoreModule.dll]UnityEngine.SendMouseEvents
 
(Filename:  Line: 143)

Unable to find method PostprocessStacktrace in [UnityEngine.CoreModule.dll]UnityEngine.StackTraceUtility
 
(Filename:  Line: 143)

Unable to find method Internal_ClearManagedDescriptors in [UnityEngine.XRModule.dll]UnityEngine.Experimental.Internal_SubsystemDescriptors
 
(Filename:  Line: 143)

Unable to find method Internal_InitializeManagedDescriptor in [UnityEngine.XRModule.dll]UnityEngine.Experimental.Internal_SubsystemDescriptors
 
(Filename:  Line: 143)

Unable to find method Internal_ClearManagedInstances in [UnityEngine.XRModule.dll]UnityEngine.Experimental.Internal_SubsystemInstances
 
(Filename:  Line: 143)

Unable to find method Internal_InitializeManagedInstance in [UnityEngine.XRModule.dll]UnityEngine.Experimental.Internal_SubsystemInstances
 
(Filename:  Line: 143)

Unable to find method Internal_RemoveInstanceByPtr in [UnityEngine.XRModule.dll]UnityEngine.Experimental.Internal_SubsystemInstances
 
(Filename:  Line: 143)

Crash!!!
SymInit: Symbol-SearchPath: '.;E:\;E:;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 534, UserName: 'tyriq'
OS-Version: 10.0.0
E:\FAForeverMapEditor.exe:FAForeverMapEditor.exe (00007FF712BF0000), size: 671744 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2018.2.2.36079
C:\Windows\SYSTEM32\ntdll.dll:ntdll.dll (00007FFE85D20000), size: 2031616 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.418
C:\Windows\System32\KERNEL32.DLL:KERNEL32.DLL (00007FFE851A0000), size: 729088 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.329
C:\Windows\System32\KERNELBASE.dll:KERNELBASE.dll (00007FFE83930000), size: 2764800 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.535
E:\UnityPlayer.dll:UnityPlayer.dll (00007FFE28C60000), size: 23744512 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2018.2.2.36079
C:\Windows\System32\CRYPT32.dll:CRYPT32.dll (00007FFE83790000), size: 1347584 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.476
C:\Windows\System32\ucrtbase.dll:ucrtbase.dll (00007FFE83580000), size: 1024000 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\SYSTEM32\HID.DLL:HID.DLL (00007FFE81800000), size: 57344 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\WindowsCodecs.dll:WindowsCodecs.dll (00007FFE7D1E0000), size: 1765376 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\MSASN1.dll:MSASN1.dll (00007FFE82C70000), size: 73728 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\msvcrt.dll:msvcrt.dll (00007FFE85420000), size: 647168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.0.18362.1
C:\Windows\System32\USER32.dll:USER32.dll (00007FFE85860000), size: 1654784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.535
C:\Windows\System32\RPCRT4.dll:RPCRT4.dll (00007FFE856D0000), size: 1179648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.476
C:\Windows\System32\win32u.dll:win32u.dll (00007FFE83900000), size: 135168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.535
C:\Windows\System32\GDI32.dll:GDI32.dll (00007FFE84870000), size: 155648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\combase.dll:combase.dll (00007FFE84480000), size: 3366912 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.449
C:\Windows\System32\gdi32full.dll:gdi32full.dll (00007FFE83BE0000), size: 1654784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.535
C:\Windows\System32\msvcp_win.dll:msvcp_win.dll (00007FFE82D60000), size: 647168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\System32\bcryptPrimitives.dll:bcryptPrimitives.dll (00007FFE82CB0000), size: 524288 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.295
C:\Windows\System32\ole32.dll:ole32.dll (00007FFE85040000), size: 1400832 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.113
C:\Windows\System32\advapi32.dll:advapi32.dll (00007FFE847C0000), size: 667648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.329
C:\Windows\System32\sechost.dll:sechost.dll (00007FFE84FA0000), size: 618496 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.267
C:\Windows\SYSTEM32\VERSION.dll:VERSION.dll (00007FFE7D9D0000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\SHLWAPI.dll:SHLWAPI.dll (00007FFE85BB0000), size: 335872 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\SETUPAPI.dll:SETUPAPI.dll (00007FFE83F90000), size: 4653056 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\cfgmgr32.dll:cfgmgr32.dll (00007FFE83D80000), size: 303104 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\System32\bcrypt.dll:bcrypt.dll (00007FFE82D30000), size: 155648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.267
C:\Windows\System32\SHELL32.dll:SHELL32.dll (00007FFE848B0000), size: 7229440 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.535
C:\Windows\System32\shcore.dll:shcore.dll (00007FFE85AD0000), size: 692224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\windows.storage.dll:windows.storage.dll (00007FFE82E00000), size: 7860224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.535
C:\Windows\System32\profapi.dll:profapi.dll (00007FFE82C90000), size: 126976 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\powrprof.dll:powrprof.dll (00007FFE82C00000), size: 303104 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\UMPDC.dll:UMPDC.dll (00007FFE82BF0000), size: 65536 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\System32\kernel.appcore.dll:kernel.appcore.dll (00007FFE82C50000), size: 69632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\cryptsp.dll:cryptsp.dll (00007FFE838E0000), size: 94208 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\WS2_32.dll:WS2_32.dll (00007FFE857F0000), size: 454656 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\System32\OLEAUT32.dll:OLEAUT32.dll (00007FFE854C0000), size: 802816 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.535
C:\Windows\SYSTEM32\OPENGL32.dll:OPENGL32.dll (00007FFE3D8F0000), size: 1400832 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\System32\IMM32.dll:IMM32.dll (00007FFE85B80000), size: 188416 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\SYSTEM32\WINMM.dll:WINMM.dll (00007FFE7FF00000), size: 147456 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\GLU32.dll:GLU32.dll (00007FFE3D730000), size: 180224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\SYSTEM32\WINHTTP.dll:WINHTTP.dll (00007FFE7B5B0000), size: 983040 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.449
C:\Windows\SYSTEM32\WINMMBASE.dll:WINMMBASE.dll (00007FFE7FED0000), size: 184320 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\dxcore.dll:dxcore.dll (00007FFE818D0000), size: 131072 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\system32\uxtheme.dll:uxtheme.dll (00007FFE80F70000), size: 626688 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.449
E:\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll:mono-2.0-bdwgc.dll (00007FFE286A0000), size: 5996544 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\System32\PSAPI.DLL:PSAPI.DLL (00007FFE848A0000), size: 32768 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\MSWSOCK.dll:MSWSOCK.dll (00007FFE82400000), size: 421888 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\CRYPTBASE.DLL:CRYPTBASE.DLL (00007FFE825D0000), size: 49152 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\System32\MSCTF.dll:MSCTF.dll (00007FFE85260000), size: 1265664 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.535
C:\Windows\SYSTEM32\d3d11.dll:d3d11.dll (00007FFE7FF30000), size: 2469888 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\SYSTEM32\dxgi.dll:dxgi.dll (00007FFE818F0000), size: 962560 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\System32\DriverStore\FileRepository\u0346830.inf_amd64_35731e557194973d\B345901\aticfx64.dll:aticfx64.dll (00007FFE7BB80000), size: 1953792 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 26.20.12028.2
C:\Windows\System32\DriverStore\FileRepository\u0346830.inf_amd64_35731e557194973d\B345901\atiuxp64.dll:atiuxp64.dll (00007FFE79000000), size: 217088 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 26.20.12028.2
C:\Windows\System32\DriverStore\FileRepository\u0346830.inf_amd64_35731e557194973d\B345901\atidxx64.dll:atidxx64.dll (00007FFE77DF0000), size: 17821696 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 26.20.12028.2
C:\Windows\SYSTEM32\apphelp.dll:apphelp.dll (00007FFE80EA0000), size: 585728 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\amdihk64.dll:amdihk64.dll (00007FFE77B00000), size: 176128 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 1.0.0.0
C:\Windows\System32\clbcatq.dll:clbcatq.dll (00007FFE85A20000), size: 663552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2001.12.10941.16384
C:\Windows\system32\wbem\wbemprox.dll:wbemprox.dll (00007FFE74680000), size: 69632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\wbemcomn.dll:wbemcomn.dll (00007FFE76D30000), size: 540672 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\system32\wbem\wbemsvc.dll:wbemsvc.dll (00007FFE73170000), size: 81920 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\system32\wbem\fastprox.dll:fastprox.dll (00007FFE73C70000), size: 1052672 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\amsi.dll:amsi.dll (00007FFE73E90000), size: 86016 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\USERENV.dll:USERENV.dll (00007FFE82B10000), size: 151552 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\ProgramData\Microsoft\Windows Defender\platform\4.18.1911.3-0\MpOav.dll:MpOav.dll (00007FFE6C920000), size: 286720 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 4.18.1911.3
C:\Windows\System32\MMDevApi.dll:MMDevApi.dll (00007FFE7E020000), size: 466944 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\System32\DEVOBJ.dll:DEVOBJ.dll (00007FFE82A10000), size: 172032 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.387
C:\Windows\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (00007FFE7E270000), size: 1429504 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.449
C:\Windows\SYSTEM32\wintypes.dll:wintypes.dll (00007FFE7E840000), size: 1388544 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.449
C:\Windows\SYSTEM32\resourcepolicyclient.dll:resourcepolicyclient.dll (00007FFE812A0000), size: 81920 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\dbghelp.dll:dbghelp.dll (00007FFE73190000), size: 2048000 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1
C:\Windows\SYSTEM32\SspiCli.dll:SspiCli.dll (00007FFE82AE0000), size: 192512 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.18362.1

========== OUTPUTTING STACK TRACE ==================

0x00007FFE287CA031 (mono-2.0-bdwgc) mono_get_runtime_build_info
0x00007FFE28751AE2 (mono-2.0-bdwgc) mono_perfcounters_init
0x00007FFE2875AACF (mono-2.0-bdwgc) mono_runtime_invoke
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE292514A4)
0x00007FFE292514A4 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE2924BCCB)
0x00007FFE2924BCCB (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE28ECCE34)
0x00007FFE28ECCE34 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE297BC8E4)
0x00007FFE297BC8E4 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE297BD99E)
0x00007FFE297BD99E (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE2923C405)
0x00007FFE2923C405 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE2923A440)
0x00007FFE2923A440 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE2927A5B7)
0x00007FFE2927A5B7 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE28D59C37)
0x00007FFE28D59C37 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE28D59E90)
0x00007FFE28D59E90 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE28D5BE5D)
0x00007FFE28D5BE5D (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE28F47775)
0x00007FFE28F47775 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE2913C0F9)
0x00007FFE2913C0F9 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFE297F82CA)
0x00007FFE297F82CA (UnityPlayer) (function-name not available)
0x00007FFE297F8C2B (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF712BF1207)
0x00007FF712BF1207 (FAForeverMapEditor) (function-name not available)
0x00007FFE851B7BD4 (KERNEL32) BaseThreadInitThunk
0x00007FFE85D8CED1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/Soft/AppData/Local/Temp/ozonexo3/FAF Map Editor/Crashes

**Comment by Soft-2019** [comment]
i mostly want to use the new version for the copy paste unit mechanic. Its such a pain to place thing by hand when import/export works for almost everything else

**Comment by ozonexo3** [comment]
Crash is related to Radeon graphic drivers and latest versions of UnityEngine.
Please make sure you have latest video drivers and if it still crash make sure your system is updated.

Please test it on the latest version v0.605: 
https://github.com/ozonexo3/FAForeverMapEditor/releases/tag/v0.605-alpha


If it still crash please send me latest generated crash report at:
C:/Users/Soft/AppData/Local/Temp/ozonexo3/FAF Map Editor/Crashes

With it I will be able to tell more or send Bug Report to Unity.
