### ISSUE TITLE
Suggestion: Desert dune brush

### ISSUE THREAD

**Issue by MerryPanda** [ozonexo3/FAForeverMapEditor#116]
Hello, i love desert maps and it would be nice and very convenient to have a desert dune brush

Thanks ^^

**Comment by ozonexo3** [comment]
Not sure if its a good idea. For flat, desert surfaces is better to add dunes with stratum texture and decals. Slight bumps on the terrain are only annoying because some units cant shot thru them. Thats why most good maps has only heightmap edtails on clifs.
