### ISSUE TITLE
Improve Terrain>Type usage: Add dependency or import/export

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#119]
Since I now know what Terrain Type is used for, I would be very happy if we have the opportunity to A or B to save time ;)

A. "apply selected terrain type" to create a dependency between an already used strata (textures) and a terrain type layer
- this could also be automated grass texture = grass terrain type
- but it would also be nice if we could create dependencies manually

or

B. "Import/Export Terrain Type" like strata(Textures)

![image](https://user-images.githubusercontent.com/28671151/82024600-509aca00-9690-11ea-9efa-cde26071b5bd.png)

Info-text:
It would also be a great addition if we briefly explain the function of a menu item when hovering over it with the cursor.

e.g.
Terrain type:
- all effects like dust etc. can be changed by changing terrain type
- using lava layer you can block units from entering that area

Question:
Are there any layer limitations to its usage? Or can all terrain type/s be used at once in a map?

**Comment by ozonexo3** [comment]
Added import/export in v0.607 WIP3
