### ISSUE TITLE
Improve Unit Browser search

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#120]
I find it very helpful to see the number of the selected unit.
Here you could possibly add the name, tech and defense as well to display all relevant information about a unit :)

But it would be all the better if we could find the units under the number or name in the unit browser. At the moment only search terms like tech1, tech2, tech3, defense, ... work.
![unit_browser_search](https://user-images.githubusercontent.com/28671151/82049125-1f34f500-96b6-11ea-9622-4f5192f11d3f.png)

Or you could even integrate an additional option to drag and drop the unit from the map into "unit", in order to place more of this unit.

**Comment by ozonexo3** [comment]
Added support for CodeName and Name in search field in v0.607 WIP3
