### ISSUE TITLE
Set loaded map version (v56 or v60)

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#121]
Hey, since I often work with the GPG Editor (v56 maps only) and the FAF Editor (v56 & v60 maps), I currently always have the problem that I have to change the map version button (see picture) manually if I do open a v56 map in the FAF Editor and want to save it again as v56.
![image](https://user-images.githubusercontent.com/28671151/83326676-4672f100-a276-11ea-8d89-f7410b8af8b5.png)
The solution would be to not set the map version button to v60 by default and instead always set the loaded map version (v56 or v60) as the default for the button.

Is that possible or does it create problems?
If possible, I would be very happy about this feature.

**Comment by ozonexo3** [comment]
Not sure what you mean, when loading map with version 60 or higher it marks as v60, else marks as v56. Tested it few times on many maps and dont see any issue

**Comment by badbwoi** [comment]
Hey, I just tested both versions of SCMP_012 (Theta Passage) again.
v56: /Supreme Commander/maps
v60: /Supreme Commander Forged Alliance/maps (the gpg editor crashes with this version.)

When I open the v56 version, I expect that v56 is checked, instead -at least for me- v60 is always checked...
![image](https://user-images.githubusercontent.com/28671151/87243177-194c5d80-c434-11ea-988b-3a0be4ebcc2e.png)

**Comment by ozonexo3** [comment]
Fixed in v0.607 WIP3
