### ISSUE TITLE
improve/separate map information (scenario.lua)

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#122]
Hello everybody,

currently we only have the `description` field for specifying map information such as history, credit, author, changes to previous versions, etc.

M&M staff is currently discussing ways to sensibly divide the map information into variables so that they can be stored and read separately.

**Already implemented / used by FAF:**
- `map_version = X; ` for map versioning
- `AdaptiveMap = true;` to determine whether a map is adaptive or not

**Implemented in FAF Editor (but not yet used):**
- `reclaim = {mass, energy},` total reclaim values ​​(props + units)

**Additional variables for discussion:**
- `author = 'map maker',` maybe auto-fill with username at upload
- `credit = 'content from others used in this map',` maybe append e.g. Cookie Noob if adaptive files are used via FAF editor
- `change_log = 'what has been changed compared to the previous map version'`
- `mapping_tools = 'GPG editor, FAF editor, WM, GIMP',`
- `url = 'link to map or forum';`

##
That should definitely give us advantages in the future, but ...

**1.  What do you say about the idea of ​​separating the map information?**
Is it worth the effort? Because **_it also needs to be implemented in the client and server_** to actually use and display the information of the new variables.

**2. What (other) information / variables would be useful?**

**3. And how would we deal with old maps?**
If the variable is not present, an empty string could be returned.

**Comment by RobustnessFAF** [comment]
_Additional variables for discussion:_ 1 -, 2- , 3+/- (and whether to fit and whether it is necessary), 4+ (often you want to specify for example a link to your YouTube channel or a place where people will find other information). 

Thank you for wanting to improve

**Comment by badbwoi** [comment]
Ozonex created a quick preview, how the values could be integrated in the FAF editor.
![unknown](https://user-images.githubusercontent.com/28671151/84866533-1f8c2b80-b07a-11ea-8c63-8c2f2d9dd088.png)

**Comment by ozonexo3** [comment]
Implemented in v0.606, build is now live

**Comment by badbwoi** [comment]
thanks for the implementation. Unfortunately, it currently does not look as if these variables are used promptly or at all. As far as I can remember, other issues have priority. So for the time being it will probably not be implemented in FAF. What raises the question of whether we should remove this part (for now) to avoid confusion?
