### ISSUE TITLE
decals are not rendered to map preview

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#123]
Hello everybody,

I noticed that the GPG editor is able to display decals in the map preview.
![image](https://user-images.githubusercontent.com/28671151/99226184-a12ee380-27e9-11eb-85bf-b0696ffb81d7.png)

Unfortunately the FAF editor cannot do this.
![image](https://user-images.githubusercontent.com/28671151/99226012-52814980-27e9-11eb-98ea-85e2a49dd74d.png)
I would be very happy if the FAF editor can do that too.

I'm also wondering how the map preview will look, when I upload the map to the vault.
What map preview render process is used, when a map gets uploaded?

**Comment by speed2CZ** [comment]
Afaik the preview is saved in the scmap file, so when you save it. Upload doesnt generate a new preview.

**Comment by ozonexo3** [comment]
Fixed in v0.607 WIP2
