### ISSUE TITLE
editor crashes or pastes a unit when pasting text into unit group names - same deal with markers

### ISSUE THREAD

**Issue by UnsilentMarLo** [ozonexo3/FAForeverMapEditor#126]
If you double click a unit group to edit its name and copy paste a text string from a lua file for example the editor will just paste the text into the box but also any unit that was loaded into the paste buffer will be placed on the map. 

If the paste buffer was empty before pasting the text string the editor will soft crash.

This also happens when pasting a text into the marker name field but it will crash or paste any markers youve copied before.

**Comment by ozonexo3** [comment]
Fixed in v0.607 WIP3
