### ISSUE TITLE
Save as: Fix lua file path

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#129]
**Save as** is a really lovely tool to rename a finished map without much effort.
![image](https://user-images.githubusercontent.com/28671151/103460032-69d1b300-4d13-11eb-8f00-28f8ee184eaa.png)

Unfortunately it produces an error at file level. The folder path was changed correctly but not the file.
`adaptive_moon_tables.lua` would be the correct string. 
![image](https://user-images.githubusercontent.com/28671151/103460128-23c91f00-4d14-11eb-9c94-9997f38bbb87.png)

Would be nice if this could be improved. Because the files are already renamed correctly:
![image](https://user-images.githubusercontent.com/28671151/103460235-f630a580-4d14-11eb-96d2-bf183e990ba0.png)

**Comment by ozonexo3** [comment]
Fixed in v0.607 WIP3
