### ISSUE TITLE
Symmetry not applied to Terrain Type and Adaptive Marker 

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#130]
Hey, I just noticed that the symmetry is not applied to `Terrain Type` and `Adaptive Marker`. It would be lovely if this could also be integrated.

`Terrain Type` uses the same import mask/input as strata/texture (8bit.raw/half the maps size - just tested it in GPG editor). since its related to Terrain Type I also add that the following issue here ;) https://github.com/ozonexo3/FAForeverMapEditor/issues/119

**Terrain > Type**
![Screenshot_20210102_183841](https://user-images.githubusercontent.com/28671151/103463057-d192f880-4d29-11eb-8a56-02b95d11ac77.png)

**Marker > Adaptive**
![image](https://user-images.githubusercontent.com/28671151/103463171-baa0d600-4d2a-11eb-9644-93d5b29e482f.png)

**Comment by ozonexo3** [comment]
TerrainType & AdaptiveMarkers symmetry added in v0.607 WIP3
