### ISSUE TITLE
add relevant in game radius to ARMY_X marker

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#131]
To place marker in a certain position/radius from a ARMY_X marker I created strata and decal masks so far.
![image](https://user-images.githubusercontent.com/28671151/104650426-77dde700-56b6-11eb-960e-8595bd779810.png)

But this time I misused the defense/direct fire unit radius for that...  
![image](https://user-images.githubusercontent.com/28671151/104091005-d3554280-527a-11eb-9a8d-775f9c8ecf45.png)
That's a really nice feature!

I was wondering, if we could somehow implement it for ARMY_X marker or otherwise. I have only ideas for its usage xD

Advantages:
- The ACU buildradius could be defined. A map maker will know in the editor if the ACU can reach that mex.
- It would also be nice to have the T1-T3 PD and AA ranges displayed, to see how that spawn is covered.
- adaptive radius: depending on the map and strategy, it would be nice if we could choose how many circles/steps are needed and in what offset the radius/circles should be placed.

**Comment by ozonexo3** [comment]
Added in v0.701
Option can be enabled under Markers/Layers/Spawn ranges
