### ISSUE TITLE
add more buttons to Markers > Layers for de-/select

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#132]
I really like this option!
I was wondering if tree more buttons could be added. This would give us the opportunity to de-/select Basic, Paths and AI marker at once.
![image](https://user-images.githubusercontent.com/28671151/104319438-27616080-54e1-11eb-8602-eb02a824049b.png)

**Comment by ozonexo3** [comment]
Added in **v0.701**
