### ISSUE TITLE
Loading / Placing Units

### ISSUE THREAD

**Issue by Jammer-git** [ozonexo3/FAForeverMapEditor#138]
Getting DDS file pixel format crash.

When loading an map of mine i get this crash when i delete certain units Sniper bot, Brick then its fine
Olso when trying to place the units on a new map gets me same crash
.
[Player.log](https://github.com/ozonexo3/FAForeverMapEditor/files/6055070/Player.log)

**Comment by ozonexo3** [comment]
fixed in v0.702
