### ISSUE TITLE
Maps Working oddly in Supreme Commander: FA Vanilla

### ISSUE THREAD

**Issue by DotNetRob** [ozonexo3/FAForeverMapEditor#141]
I can create maps for Supreme Commander: FA Vanilla and they load and work but seems something is off.  When I create a new skirmish with the new map some features don't appear to work properly.   Score doesn't show up in the score board and Assassination mode doesn't work(killing commander doesn't cause the rest of army to self destruct.

**Comment by Garanas** [comment]
This is likely because of a script error. Check the moholog (f9 if I'm right) for errors and then check the _script.lua file.

**Comment by DotNetRob** [comment]
@Garanas Thanks for the help.  Not sure where the extra stuff in the _script.lua file came from but after overwriting it with the example on the [wiki](https://wiki.faforever.com/index.php?title=Map_Editor), the maps works perfectly.  Thanks.
