### ISSUE TITLE
Bug with load units BP

### ISSUE THREAD

**Issue by JavikImmortal** [ozonexo3/FAForeverMapEditor#154]
Please help me with this problem
[EDITOR LOG.log](https://github.com/ozonexo3/FAForeverMapEditor/files/12392813/EDITOR.LOG.log)
![BUG FAF MAP EDITOR](https://github.com/ozonexo3/FAForeverMapEditor/assets/76865147/30881e7d-08b1-4ef2-b7b2-2f41583ef1ec)

**Comment by ozonexo3** [comment]
Dont know why, but somehow it failed on parsing LUA template files like `UAL0001_unit.bp`.

**Comment by JavikImmortal** [comment]
The most interesting all work just a month ago, 
the only thing I did was clean the registry not so long ago
