### ISSUE TITLE
Center By Angle Range Seems Arbitrarly limited

### ISSUE THREAD

**Issue by chainingsolid** [ozonexo3/FAForeverMapEditor#2]
The limit of 2 - 8, appears to be an arbitrary restriction, on the number of rotation steps. Given FAF supports up to 16 players, that would seem to be a logical, maximum, but I see no reason to not let it go as high as possible, buggyness permitting. The nice player count of 12, (which factors into 2x2x3), which allows 2 and 3 team games, with up to 6 players per team, would be nice to have in the range of rotation spokes at least.

**Comment by ozonexo3** [comment]
I increased max number of rotations steps to 16. It should be ok for now. Editor need to generate brush data for every symmetry and than can cause some long times when changing brush.
