### ISSUE TITLE
Props selection

### ISSUE THREAD

**Issue by ozonexo3** [ozonexo3/FAForeverMapEditor#22]
Support for props selection/move/rotate tool

**Comment by ozonexo3** [comment]
- Hide selected props
- Hide all props of selected types
- Unhide all

**Comment by wgabel** [comment]
Should this be done with current UnitsInfo_Units.cs and UnitInstance? Or use PropGameObject? As I understand, the UnitInstance is not suited for this. I suggest extending this to separate controller.

**Comment by ozonexo3** [comment]
This is already implemented, forgot about closing this issue.

Every type has its own instance class and controller class. Units has implemented custom renderer that uses instancing to display them. Props were implemented many months (or years) before so they are just standard gameobjects with renderers.
