### ISSUE TITLE
Decal Translation and Rotation: Wrong Orientation of Translation Arrows

### ISSUE THREAD

**Issue by WolfFinster** [ozonexo3/FAForeverMapEditor#4]
1. Select a decal that has already been placed on the map
2. Select rotation mode for decals
3. rotate decal
4. select translation mode for decals
5. move decal and observe translation arrow pointing in the wrong direction, observe translation arrows acquiring the correct orientation once you release LMB

**Comment by ozonexo3** [comment]
Fixed
