### ISSUE TITLE
NavalExclude marker type

### ISSUE THREAD

**Issue by ozonexo3** [ozonexo3/FAForeverMapEditor#57]
Add support for NavalExclude marker

**Comment by ozonexo3** [comment]
Example: scmp_10 sung island

**Comment by ozonexo3** [comment]
That marker don exist in that example. Where is it then? Cant find it

**Comment by IIe4eHer** [comment]
last marker in _save.lua file
                ['Naval Exclude 00'] = {
                    ['color'] = STRING( 'ff0000AA' ),
                    ['hint'] = BOOLEAN( true ),
                    ['type'] = STRING( 'Naval Exclude' ),
                    ['prop'] = STRING( '/env/common/props/markers/M_CombatZone_prop.bp' ),
                    ['orientation'] = VECTOR3( 0, 6.75917e-005, 0 ),
                    ['position'] = VECTOR3( 877.5, 17.5, 33.5 ),
                },
but in crachlog without space
ArgumentException: Requested value 'NavalExclude' was not found.
