### ISSUE TITLE
Crashing on File Save

### ISSUE THREAD

**Issue by SpyEmanciator** [ozonexo3/FAForeverMapEditor#64]
Log:

[crashlog.zip](https://github.com/ozonexo3/FAForeverMapEditor/files/2152818/crashlog.zip)

**Comment by SpyEmanciator** [comment]
The map apparently gets saved so no work loss, but the editor has to be hard stopped in windows.

**Comment by SpyEmanciator** [comment]
OK just lost some work. waiting for fix to continue work.

**Comment by ozonexo3** [comment]
@SpyEmanciator 
1. Looks like editor dont have write access or somethink like that:
UnauthorizedAccessException: Access to the path "C:\Program Files\FAF MAPED\FAForeverMapEditor_Data\MapsBackup" is denied.

2. Editor crashed somehow on adaptive markers, can you give me your map so I can check why?

3. Editor also crashed when you tried to change marker name to Army_3. That looks like a bug, need to test it.

**Comment by SpyEmanciator** [comment]
ah i see, i put the files in program files, but there is no traditional
installer to set up rights so i'll move it out somewhere else.

**Comment by ozonexo3** [comment]
All bugs found and fixed in v0.601
