### ISSUE TITLE
Edit undo/redo list

### ISSUE THREAD

**Issue by SpyEmanciator** [ozonexo3/FAForeverMapEditor#67]
Undo list is removed on new action

**Comment by zkov96** [comment]
Ozonexo3, can we use new undo system for list functional?

**Comment by SpyEmanciator** [comment]
so I got more undo's not sure what went wrong, i twas placing a  marker

**Comment by ozonexo3** [comment]
I think its related to that bug:
https://github.com/ozonexo3/FAForeverMapEditor/issues/28

Undo for markers is not properly registered in some cases.
