### ISSUE TITLE
Decal Specular drew awkward square

### ISSUE THREAD

**Issue by SpyEmanciator** [ozonexo3/FAForeverMapEditor#69]
![square](https://user-images.githubusercontent.com/40737134/42173366-c5a078c2-7dec-11e8-8aef-e5aaa54a8775.png)

How can I delete this?

**Comment by SpyEmanciator** [comment]
Also map upload for you to check out! 👍 
[NS Theatre.zip](https://github.com/ozonexo3/FAForeverMapEditor/files/2155844/NS.Theatre.zip)

**Comment by ozonexo3** [comment]
Decal don't exist on your map. It might be rendering/refresh bug. Get FAF Map Editor v0.601 and report me when you encounter it again. If there will be an error, then editor will notify you.

Btw. i also changed file names in your map, to prevent "Four corners" bug. New release of map editor will prevent wrong file names.
[NS_Theatre_tex.zip](https://github.com/ozonexo3/FAForeverMapEditor/files/2157587/NS_Theatre_tex.zip)

**Comment by SpyEmanciator** [comment]
@ozonexo3 OK, I have what looks to be a polished low light version. Can you do a quick sweep for polish and tell me what process you use for balancing? After this is complete I will build the video series and promote your donation link ; )

**Comment by SpyEmanciator** [comment]
@ozonexo3 

[NS Theatre.zip](https://github.com/ozonexo3/FAForeverMapEditor/files/2160372/NS.Theatre.zip)

No problems with this that i see. Can we get it approved for 1v1s and multiplay elo?

**Comment by ozonexo3** [comment]
@SpyEmanciator this is not place to talk about that. Ask on M&M discord or FAF forum. I didn't make any map for a long time, so I don't think I'm the right person you want to ask about balance. But you can ask me for any technical stuff or questions about using editor.

Anyway i have too much work with editor to help you do some maps, but there will be probably few map authors that will find some time to help you. Mapping community is getting bigger every day.

I'm now finishing Wiki page with all information about using editor and map making process and I also writing script for official video tutorials.
