### ISSUE TITLE
save as file pathing

### ISSUE THREAD

**Issue by SpyEmanciator** [ozonexo3/FAForeverMapEditor#79]
Save as needs a new folder name/ file name system to get the .v0001 correct for upload to prevent 4 corners problem.

**Comment by SpyEmanciator** [comment]
[Turtle_Theater.v0001.zip](https://github.com/ozonexo3/FAForeverMapEditor/files/2163689/Turtle_Theater.v0001.zip)

**Comment by ozonexo3** [comment]
"Save as" don't remove "v0001" from folder name if folder with versioning were chosen.
