### ISSUE TITLE
decals

### ISSUE THREAD

**Issue by SpyEmanciator** [ozonexo3/FAForeverMapEditor#94]
Decals need an intensity level. Also is there a folder for changing/adding new decals?

**Comment by IIe4eHer** [comment]
https://wiki.faforever.com/index.php?title=FA_Forever_Map_Editor#Custom_resources

**Comment by ozonexo3** [comment]
Can't add any modifications to decals, game engine don't support that.

You can make your own decals and use them as custom resources.
